### ISSUE TITLE
BMA456 Accel 11 Click SPI on Thunderboard

### ISSUE THREAD

**Issue by Lucifer182** [SiliconLabs/platform_hardware_drivers#11]
Hello,
I am using the Accel 11 Click with the BMA456 on a Thunderboard EFR32BG22 PCB4184A Rev A01 and Gecko SDK 4.20.
I opened like described a new C project and copied the needed files. I also edited the app.c accordingly and it builds and I can flash it.
Unfortunately there is nothing to be seen on the terminal. I also edited the bma400.h acoordingly to the data sheet of the BMA456.
Is the code for the BMA400 Accel 5 Click usable?

**Comment by silabs-HopN** [comment]
Hi @Lucifer182,
Thanks for your feedback!
Today We tried to check the BMA400 Accel 5 driver with the Thunderboard BG22 (BRD4184A). It seems that everything is ok as picture below. 
So please let me know what terminal are you using to show logs?
If you use the Console that is integrated in Simplicity Studio, make sure that Serial 1 is selected, and you need to hit Enter in the terminal for the first time to active it.
Please check and Let me know if something is wrong.

![log](https://user-images.githubusercontent.com/76993461/220814136-09dcbf4b-faef-4635-874b-3acfa4993a67.png)

**Comment by Lucifer182** [comment]
Thanks for the fast help. 

I am using the integrated console of Simplicity Studio. I didn't know that hitting Enter was mandatory, so that was the problem.
As I said I am using the Accel 11 with BMA456. After some changes, most of the registers are defined in the same way, in the bma400.h it was usable and I got something on the Console.

Best regards and thanks again.
You really did a great job with the driver.
