### ISSUE TITLE
platform_hardware_drivers/audio_dac_uda1334a

### ISSUE THREAD

**Issue by silabs-DenverL** [SiliconLabs/platform_hardware_drivers#6]
The .settings\com.silabs.ss.framework.ide.project.sls.core.prefs introduce warning when import to SS v5.
You could get this file if you unzip the audio_dac_simple.sls.

The content of this file:
copiedFilesOriginState={"/home/das/git/platform_hardware_drivers_staging/audio_dac_uda1334a/src/audio_dac.c"\:"413989693","/home/das/git/platform_hardware_drivers_staging/audio_dac_uda1334a/inc/audio_dac_config.h"\:"854308567","/home/das/git/platform_hardware_drivers_staging/audio_dac_uda1334a/test/audio_dac_simple.c"\:"1224425329","/home/das/git/platform_hardware_drivers_staging/audio_dac_uda1334a/test/audio_data.h"\:"-1774500112","/home/das/git/platform_hardware_drivers_staging/audio_dac_uda1334a/inc/audio_dac.h"\:"1662660018"}
eclipse.preferences.version=1

**Comment by silabs-DenverL** [comment]
This apply to example like platform_applications/platform_adc_rng/

**Comment by silabs-marao** [comment]
The audio dac issue has been fixed in 837a9dd2d1ed23d7d0fa4eea3f8c2c3eb0966ccc. @silabs-DenverL - please open a ticket in the platform_applications queue for the platform_adc_rng issue. Let us keep bugs opened for different repos separate. Thanks!
