### ISSUE TITLE
oled_ssd1306_i2c

### ISSUE THREAD

**Issue by silabs-DenverL** [SiliconLabs/platform_hardware_drivers#7]
build failure on SDK 3.2.1
C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.2/platform/driver/button/src/sl_simple_button.c:55: undefined reference to `sl_simple_button_array'
collect2.exe: error: ld returned 1 exit status

**Comment by silabs-marao** [comment]
This issue cannot be reproduced. I tested this against GSDK 3.1.1 and 3.2.2 and could not see the build failure. Please also note that sl_simple_button_array is defined in sl_simple_button.c file. Please update your SDK and try again. 

`
...
static const uint16_t debounce_window = (uint16_t)(0xffff << (SL_SIMPLE_BUTTON_DEBOUNCE_BITS + 1));

extern const sl_button_t *sl_simple_button_array[];
extern const uint8_t simple_button_count;
...
`
